version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        GID: ${GID:-1000}
        UID: ${UID:-1000}
    command: ["bundle", "exec", "ruby", "./main.rb"]
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      TZ: Asia/Tokyo
      REDIS_URL: redis://redis:6379
      SLACK_API_TOKEN: $SLACK_API_TOKEN
      PORT: 8080
    volumes:
      - .:/home/dev/trans-movie-bot
    init: true
    stdin_open: true
    tty: true
  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
