FROM ruby:3

# add node
ENV PORT=3000
ENV TZ='Asia/Tokyo'

RUN groupadd --gid 1000 runner \
  && useradd --uid 1000 --gid runner --shell /bin/bash --create-home runner
USER runner
ENV APP_ROOT /home/runner/trans-movie-bot
RUN mkdir -p ${APP_ROOT}
WORKDIR ${APP_ROOT}
COPY --chown=runner:runner . ${APP_ROOT}/
RUN bundle install
CMD ["bundle", "exec", "ruby", "main.rb"]
EXPOSE ${PORT}